spring.application.name=SteamWebAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

# specifies ollama base url and model to use
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.chat.options.model=gemma4:31b

# timeout instructions for ollama
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.keep-alive=10m
spring.ai.ollama.chat.options.num-predict=1000

spring.http.client.connect-timeout=5s
spring.ai.ollama.init.timeout=5m
