spring.application.name=SteamWebAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.chat.options.model=gemma4:31b
spring.ai.ollama.chat.options.temperature=0.7